### ISSUE TITLE
SCSS Not working

### ISSUE THREAD

**Issue by naodya** [TimMikeladze/tsup-react-package-starter#51]
- Is there a way to to include scss? Do you have a guide for that?

**Comment by TimMikeladze** [comment]
@naodya try this out

First enable postcss support - https://tsup.egoist.dev/#css-support

Then configure postcss to add some scss related plugins to replicate scss functionality, for example with this plugin: 
https://github.com/postcss/postcss-scss

Or this one: https://github.com/csstools/postcss-sass

Let me know if this works for you or if there are any other questions with this approach.
