### ISSUE TITLE
Styles?

### ISSUE THREAD

**Issue by noudadrichem** [TimMikeladze/tsup-react-package-starter#71]
Am I missing something or is styling completely ignored in this setup? I like the setup but am unable to make .css or .scss work. 

I'm trying to extend with postcss and tsup but so far no result. Do you have any examples on how to implement it using this setup?

**Comment by TimMikeladze** [comment]
Hi @noudadrichem I've updated the codebase with an example usage of a css file (without postcss). Run `yarn build && ls dist` and there should be a css file called `index.css` in the `dist` folder. 

Also take note of the `injectStyle` option that `tsup` accepts. This is set to `false` by default, but if you set it to `true` then the styles will be injected into your built react component. When `injectStyle` is enabled then no `.css` files will be included in the `dist` folder.

**Comment by noudadrichem** [comment]
Hi @TimMikeladze, Thanks for the quick response!
I did not know about the `injectStyle` option in tsup. I was reading up on tsup and that it supports PostCSS but it kept exporting the styles to a `.css` file inside the dist folder. I will try with `injectStyle`!

Side question; Have you tried adding Radix components?

**Comment by TimMikeladze** [comment]
> Hi @TimMikeladze, Thanks for the quick response!
> 
> I did not know about the `injectStyle` option in tsup. I was reading up on tsup and that it supports PostCSS but it kept exporting the styles to a `.css` file inside the dist folder. I will try with `injectStyle`! 
> 
> 
> 
> Side question; Have you tried adding Radix components and/or the use of `.scss` files?

Glad I could. 

I have not tried either of those things.
