### ISSUE TITLE
'React' must be in scope when using JSX

### ISSUE THREAD

**Issue by encho** [TimMikeladze/tsup-react-package-starter#81]
`11:3  error  'React' must be in scope when using JSX  react/react-in-jsx-scope`

I am encountering the above issue when building a component that does not import React (if I still import React babel is commenting out that import). I'd appreciate some hint on how to solve this. Many thanks!

**Comment by TimMikeladze** [comment]
> `11:3  error  'React' must be in scope when using JSX  react/react-in-jsx-scope`
> 
> 
> 
> I am encountering the above issue when building a component that does not import React (if I still import React babel is commenting out that import). I'd appreciate some hint on how to solve this. Many thanks!

Is the file extension that error is coming from .jsx / .tsx ? If you don't have any react jsx than I believe you can just rename the file extension to .ts or .js and the error will go away I think. 

Alternatively this is an eslint error, so just disable it in the config. 


"react/react-in-jsx-scope": "off"


-----


Thank you for bringing this up. Maybe I will add that eslint rule into the config by default. 


I hope you find this starter kit useful 😀

**Comment by encho** [comment]
so i could now commit and build with this test component. it works because of your suggestion to add `"react/react-in-jsx-scope": "off"` in the `.eslintrc.js` file.

```
import './BarChart.css';

// import React from 'react';

export type BarChartProps = {
  data: number[];
};

export const BarChart = (props: BarChartProps) => (
  <div className="BarChart">
    BarChart
    <div>{JSON.stringify(props.data)}</div>
  </div>
);
```

i'll now proceed with setting my lib up - many thanks!

**Comment by TimMikeladze** [comment]
I updated the eslint config to include this rule out of the box now.
