### ISSUE TITLE
CSS issue in released package

### ISSUE THREAD

**Issue by encho** [TimMikeladze/tsup-react-package-starter#82]
Hello, I have now successfully released my package `ibcs-charts`. the original `Example` component is also still there and can be imported. The CSS styles have been lost however. Would you know the reason?

Many thanks!

**Comment by encho** [comment]
solved with `"injectStyle": true` in `tsup` configuration in `package.json`.

**Comment by TimMikeladze** [comment]
Congrats on the package release! 

Yeah that's a potential solution. I mention some other different ways to handing css in the readme.
